# Generated by Django 5.0.2 on 2024-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
