# Generated by Django 5.0.2 on 2024-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
