# Generated by Django 3.2.23 on 2024-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(editable=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_tel_number', models.CharField(max_length=50)),
                ('customer_address_one', models.CharField(max_length=50)),
                ('customer_address_two', models.CharField(max_length=50)),
                ('customer_address_three', models.CharField(max_length=50)),
                ('customer_address_four', models.CharField(max_length=50)),
                ('customer_postcode', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('order_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
