# Generated by Django 5.0.2 on 2024-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='county',
            field=models.CharField(default=111111, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='postcode',
            field=models.CharField(default=111111, max_length=20),
            preserve_default=False,
        ),
    ]
