# Generated by Django 5.0.2 on 2024-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderplaceholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaceholder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderplaceholder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderplaceholder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderplaceholder',
            name='total',
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='county',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='email',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='full_name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='order_number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='phone_number',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='postcode',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='product_id',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='street_address1',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='street_address2',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderplaceholder',
            name='town_or_city',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaceholder',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
