# Generated by Django 5.0.2 on 2024-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_orderplaceholder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaceholder',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
