# Generated by Django 5.0.2 on 2024-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_orderplaceholder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaceholder',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
