# Generated by Django 5.0.2 on 2024-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderplaceholder_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_cost',
            new_name='default_price',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_cost',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_address_four',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_address_one',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_address_three',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_address_two',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_postcode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_tel_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='county',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='full_name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='postcode',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='street_address1',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='street_address2',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='town_or_city',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
