# Generated by Django 5.0.2 on 2024-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_order_cost_orders_default_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaceholder',
            name='product_name',
            field=models.CharField(default='Test', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default='Test', editable=False, max_length=32),
        ),
    ]
