# Generated by Django 5.0.2 on 2024-03-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderplaceholder_product_name_orders_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaceholder',
            old_name='total_price',
            new_name='sub_price',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_price',
            new_name='sub_price',
        ),
    ]
