# Generated by Django 5.0.2 on 2024-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_rename_total_price_orderplaceholder_sub_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaceholder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
