# Generated by Django 5.0.2 on 2024-03-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('checkout', '0009_orderplaceholder_total_price_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.userprofile'),
        ),
    ]
