# Generated by Django 5.0.2 on 2024-03-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orders_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_profile',
        ),
    ]
