# Generated by Django 5.0.2 on 2024-03-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_delete_users'),
        ('checkout', '0011_remove_orders_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.userprofile'),
        ),
    ]
