# Generated by Django 5.0.2 on 2024-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_rename_default_price_orders_delivery_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineitem_total',
            new_name='order_total',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='stripe_pid',
            new_name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='original_bag',
        ),
    ]
