# Generated by Django 5.0.2 on 2024-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_title',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
