# Generated by Django 5.0.2 on 2024-04-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_remove_reviews_product'),
    ]

    
