# Generated by Django 5.0.2 on 2024-04-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_rename_order_total_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order_total',
            new_name='lineitem_total',
        ),
    ]
