# Generated by Django 5.0.2 on 2024-04-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('product_name', models.CharField(default='Test', editable=False, max_length=32)),
                ('product_id', models.IntegerField(default=1, editable=False)),
                ('quantity', models.IntegerField(default=1, editable=False)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sub_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=32)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basket.basket')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_item', to='accounts.userprofile')),
            ],
        ),
    ]
