# Generated by Django 5.0.2 on 2024-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user_id',
        ),
        migrations.AddField(
            model_name='basket',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='basket',
            name='order_number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
