# Generated by Django 5.0.2 on 2024-03-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_basket_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_price',
            new_name='sub_price',
        ),
    ]
