# Generated by Django 5.0.2 on 2024-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_rename_total_price_basket_sub_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
