# Generated by Django 5.0.2 on 2024-03-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_default_country'),
        ('basket', '0009_basketitem_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_item', to='accounts.userprofile'),
        ),
    ]
