# Generated by Django 3.2.23 on 2024-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_long_description',
        ),
        migrations.AddField(
            model_name='products',
            name='fibre_source',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='protein_source',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
