# Generated by Django 5.0.2 on 2024-03-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_email_userprofile_full_name'),
        ('products', '0007_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.userprofile'),
        ),
    ]
