# Generated by Django 5.0.2 on 2024-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favourites_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='calorie_content',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5')], default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='carbohydrate_content',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='carbohydrate_sugar_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='chef_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='fat_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fibre_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='protein_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='salt_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='saturated_fat_content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
