# Generated by Django 5.0.2 on 2024-04-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_chefmessages_remove_products_chef_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_rating',
        ),
    ]
